import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Product, Supplier } from '../types';
import { ShoppingCart, AlertCircle } from 'lucide-react';

interface PurchaseOrderModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: {
    productId: string;
    productName: string;
    supplierId: string;
    supplierName: string;
    quantity: number;
    unitPrice: number;
    expectedDelivery: string;
    notes: string;
    autoGenerated: boolean;
  }) => void;
  products: Product[];
  suppliers: Supplier[];
  preselectedProductId?: string;
}

export const PurchaseOrderModal: React.FC<PurchaseOrderModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  products,
  suppliers,
  preselectedProductId,
}) => {
  const [formData, setFormData] = useState({
    productId: preselectedProductId || '',
    supplierId: '',
    quantity: '',
    unitPrice: '',
    expectedDelivery: '',
    notes: '',
  });

  const [error, setError] = useState('');
  const [suggestedQuantity, setSuggestedQuantity] = useState(0);

  useEffect(() => {
    if (preselectedProductId) {
      setFormData(prev => ({ ...prev, productId: preselectedProductId }));
    }
  }, [preselectedProductId]);

  useEffect(() => {
    if (formData.productId) {
      const product = products.find(p => p.id === formData.productId);
      if (product) {
        // Suggest ordering enough to reach 2x minimum stock
        const suggested = Math.max(0, (product.minStock * 2) - product.stockQuantity);
        setSuggestedQuantity(suggested);
        if (!formData.quantity) {
          setFormData(prev => ({ ...prev, quantity: suggested.toString() }));
        }
        // Set unit price if available
        if (!formData.unitPrice && product.costPrice) {
          setFormData(prev => ({ ...prev, unitPrice: product.costPrice.toString() }));
        }
      }
    }
  }, [formData.productId, products, formData.quantity, formData.unitPrice]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const selectedProduct = products.find(p => p.id === formData.productId);
    const selectedSupplier = suppliers.find(s => s.id === formData.supplierId);
    
    if (!selectedProduct || !selectedSupplier) {
      setError('Please select both product and supplier');
      return;
    }

    const quantity = parseInt(formData.quantity);
    const unitPrice = parseFloat(formData.unitPrice);

    if (isNaN(quantity) || quantity <= 0) {
      setError('Please enter a valid quantity');
      return;
    }

    if (isNaN(unitPrice) || unitPrice <= 0) {
      setError('Please enter a valid unit price');
      return;
    }

    if (!formData.expectedDelivery) {
      setError('Please select expected delivery date');
      return;
    }

    const purchaseOrder: Omit<any, 'orderNumber' | 'orderDate' | 'createdBy'> = {
      productId: formData.productId,
      productName: selectedProduct.name,
      supplierId: formData.supplierId,
      supplierName: selectedSupplier.name,
      quantity,
      unitPrice,
      expectedDelivery: formData.expectedDelivery,
      notes: formData.notes,
      autoGenerated: !!preselectedProductId,
    };

    onSubmit(purchaseOrder as any);

    // Reset form
    setFormData({
      productId: '',
      supplierId: '',
      quantity: '',
      unitPrice: '',
      expectedDelivery: '',
      notes: '',
    });
    setError('');
  };

  const selectedProduct = products.find(p => p.id === formData.productId);
  const totalAmount = parseFloat(formData.quantity || '0') * parseFloat(formData.unitPrice || '0');

  // Filter suppliers that supply the selected product
  const filteredSuppliers = formData.productId
    ? suppliers.filter(s =>
        s.productsSupplied.some(ps => ps === formData.productId)
      )
    : suppliers;

  const relevantSuppliers = filteredSuppliers.length > 0 ? filteredSuppliers : suppliers;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShoppingCart className="w-5 h-5 text-blue-600" />
            Create Purchase Order
            {preselectedProductId && (
              <span className="text-sm text-orange-600 font-normal">(Low Stock Alert)</span>
            )}
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}

          {preselectedProductId && selectedProduct && (
            <div className="bg-orange-50 border border-orange-200 px-4 py-3 rounded">
              <div className="flex items-start gap-2">
                <AlertCircle className="w-5 h-5 text-orange-600 mt-0.5" />
                <div className="text-sm text-orange-800">
                  <strong>{selectedProduct.name}</strong> is below minimum stock level.
                  <br />
                  Current: <strong>{selectedProduct.stockQuantity}</strong> | 
                  Minimum: <strong>{selectedProduct.minStock}</strong> |
                  Suggested Order: <strong>{suggestedQuantity}</strong> units
                </div>
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Product */}
            <div className="space-y-2">
              <Label htmlFor="product">Product *</Label>
              <select
                id="product"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={formData.productId}
                onChange={(e) => setFormData({ ...formData, productId: e.target.value })}
                required
                disabled={!!preselectedProductId}
              >
                <option value="">Select Product</option>
                {products
                  .filter(p => p.status === 'Active')
                  .map((product) => (
                    <option key={product.id} value={product.id}>
                      {product.name} - Stock: {product.stockQuantity} (Min: {product.minStock})
                    </option>
                  ))}
              </select>
            </div>

            {/* Supplier */}
            <div className="space-y-2">
              <Label htmlFor="supplier">Supplier *</Label>
              <select
                id="supplier"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={formData.supplierId}
                onChange={(e) => setFormData({ ...formData, supplierId: e.target.value })}
                required
              >
                <option value="">Select Supplier</option>
                {relevantSuppliers.map((supplier) => (
                  <option key={supplier.id} value={supplier.id}>
                    {supplier.name}
                  </option>
                ))}
              </select>
              {relevantSuppliers.length === 0 && formData.productId && (
                <p className="text-xs text-orange-600">
                  No suppliers found for this product. Showing all suppliers.
                </p>
              )}
            </div>

            {/* Quantity */}
            <div className="space-y-2">
              <Label htmlFor="quantity">Order Quantity *</Label>
              <Input
                id="quantity"
                type="number"
                min="1"
                placeholder="Enter quantity"
                value={formData.quantity}
                onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                required
              />
              {suggestedQuantity > 0 && (
                <p className="text-xs text-gray-600">
                  Suggested: {suggestedQuantity} units (to reach 2x minimum stock)
                </p>
              )}
            </div>

            {/* Unit Price */}
            <div className="space-y-2">
              <Label htmlFor="unitPrice">Unit Price *</Label>
              <Input
                id="unitPrice"
                type="number"
                step="0.01"
                min="0.01"
                placeholder="Enter unit price"
                value={formData.unitPrice}
                onChange={(e) => setFormData({ ...formData, unitPrice: e.target.value })}
                required
              />
            </div>

            {/* Expected Delivery */}
            <div className="space-y-2">
              <Label htmlFor="expectedDelivery">Expected Delivery Date *</Label>
              <Input
                id="expectedDelivery"
                type="date"
                min={new Date().toISOString().split('T')[0]}
                value={formData.expectedDelivery}
                onChange={(e) => setFormData({ ...formData, expectedDelivery: e.target.value })}
                required
              />
            </div>

            {/* Total Amount (calculated) */}
            <div className="space-y-2">
              <Label>Total Amount</Label>
              <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded-md font-semibold text-lg">
                ${totalAmount.toFixed(2)}
              </div>
            </div>

            {/* Notes */}
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="notes">Order Notes</Label>
              <textarea
                id="notes"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                rows={3}
                placeholder="Enter any special instructions or notes for this order"
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
              />
            </div>
          </div>

          {/* Order Summary */}
          {formData.productId && formData.supplierId && formData.quantity && formData.unitPrice && (
            <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
              <h4 className="font-semibold text-sm text-blue-900 mb-2">Order Summary</h4>
              <div className="text-sm text-blue-800 space-y-1">
                <p>
                  <strong>Product:</strong> {selectedProduct?.name}
                </p>
                <p>
                  <strong>Supplier:</strong> {suppliers.find(s => s.id === formData.supplierId)?.name}
                </p>
                <p>
                  <strong>Quantity:</strong> {formData.quantity} units × ${parseFloat(formData.unitPrice).toFixed(2)} = 
                  <strong className="ml-1">${totalAmount.toFixed(2)}</strong>
                </p>
                {selectedProduct && (
                  <p>
                    <strong>Stock After Delivery:</strong> {selectedProduct.stockQuantity + parseInt(formData.quantity)} units
                  </p>
                )}
              </div>
            </div>
          )}

          <div className="flex justify-end gap-3 pt-4">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit">
              Create Purchase Order
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};