// Type definitions for the Inventory Management System

export interface User {
  id: string;
  name: string;
  email: string;
  role:
    | "Admin"
    | "Inventory_Staff"
    | "Warehouse_Manager"
    | "Auditor";
  status: "Active" | "Inactive" | "Pending" | "PendingDeletion";
  workplace?: string; // Workplace/branch location
  department?: string; // Department within organization
  phone?: string; // Contact phone number
  createdAt?: string;
  emailNotifications?: boolean;
  lowStockAlerts?: boolean;
  orderNotifications?: boolean;
  pushNotifications?: boolean;
  emailDigest?: string;
  twoFactorEnabled?: boolean;
}

export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string;
  unit: string;
  costPrice: number;
  stockQuantity: number;
  minStock: number;
  status: "Active" | "Inactive";
  expirationDate?: string; // Optional expiration date for perishable items
  hasExpiration?: boolean; // Whether this product type has expiration tracking
  supplierId?: string | null; // Linked supplier
}

export interface Supplier {
  id: string;
  name: string;
  contact: string;
  email: string;
  address: string;
  description?: string;
  productsSupplied: string[];
}

export interface StockTransaction {
  id: string;
  productId: string;
  productName: string;
  type: "IN" | "OUT" | "TRANSFER" | "SHRINKAGE";
  quantity: number;
  date: string;
  user: string;
  userName?: string; // API field from backend (Prisma returns userName)
  note: string;
  status: "Pending" | "Approved" | "Rejected";
  warehouse: string;
  // Transfer specific fields
  fromWarehouse?: string;
  toWarehouse?: string;
  // Shrinkage specific fields
  shrinkageReason?:
    | "Damaged"
    | "Expired"
    | "Lost"
    | "Theft"
    | "Other";
  purchaseOrderId?: string; // Set when auto-generated by a purchase order
}

export interface PurchaseOrder {
  id: string;
  orderNumber: string;
  productId: string;
  productName: string;
  supplierId: string;
  supplierName: string;
  quantity: number;
  unitPrice: number;
  totalAmount: number;
  orderDate: string;
  expectedDelivery: string;
  status: "Draft" | "Sent" | "Received" | "Cancelled";
  createdBy: string;
  notes: string;
  autoGenerated?: boolean; // True if created by low stock alert
}

export interface DashboardStats {
  totalProducts: number;
  totalStock: number;
  lowStockItems: number;
  totalSuppliers: number;
  expiredItems?: number;
  expiringItems?: number;
  pendingOrders?: number;
  shrinkageThisMonth?: number;
}

export interface AuditLog {
  id: string;
  action: string;
  user: string;
  timestamp: string;
  details: string;
}

export interface UserActivityLog {
  id: string;
  userId: string;
  userName: string;
  action: 'Login' | 'Logout';
  timestamp: string;
  ipAddress: string;
  device: string;
  location: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  supplierId: string;
  supplierName: string;
  invoiceDate: string;
  dueDate: string;
  items: InvoiceItem[];
  subtotal: number;
  tax: number;
  totalAmount: number;
  status: 'Draft' | 'Pending' | 'Paid' | 'Cancelled';
  notes: string;
  createdBy: string;
  createdAt: string;
  purchaseOrderId?: string; // Set when auto-generated by a purchase order
}

export interface InvoiceItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}

// Product categories
export const PRODUCT_CATEGORIES = [
  "Electronics",
  "Accessories",
  "Furniture",
  "Office Supplies",
  "Dry Food",
  "Fresh Food",
  "Frozen Food",
  "Beverages",
  "Healthcare",
  "Personal Care",
  "Household",
  "Cleaning Supplies",
  "Toys & Games",
  "Sports & Outdoors",
  "Automotive",
  "Tools & Hardware",
  "Books & Media",
  "Clothing",
  "Other",
] as const;

export const WAREHOUSES = [
  "Phnom Penh Main Warehouse",
  "Siem Reap Warehouse",
  "Battambang Warehouse",
  "Sihanoukville Warehouse",
  "Kampong Cham Warehouse"
] as const;

export const WORKPLACES = [
  "Headquarters - Phnom Penh",
  "Branch Office - Siem Reap",
  "Branch Office - Battambang",
  "Branch Office - Sihanoukville",
  "Branch Office - Kampong Cham",
  "Remote",
] as const;

export const DEPARTMENTS = [
  "Operations",
  "Logistics",
  "Procurement",
  "Finance",
  "IT",
  "Administration",
  "Quality Control",
  "Customer Service",
] as const;