import { IsEnum, IsNotEmpty, IsNumber, IsOptional, IsString, IsBoolean, Min } from 'class-validator';

export class CreatePurchaseOrderDto {
  @IsString() @IsNotEmpty() productId: string;
  @IsString() @IsNotEmpty() productName: string;
  @IsString() @IsNotEmpty() supplierId: string;
  @IsString() @IsNotEmpty() supplierName: string;
  @IsNumber() @Min(1) quantity: number;
  @IsNumber() @Min(0) unitPrice: number;
  @IsNumber() @Min(0) totalAmount: number;
  @IsString() @IsNotEmpty() expectedDelivery: string;
  @IsOptional() @IsEnum(['Draft', 'Sent', 'Received', 'Cancelled']) status?: string;
  @IsOptional() @IsString() notes?: string;
  @IsOptional() @IsBoolean() autoGenerated?: boolean;
}

export class UpdatePurchaseOrderDto {
  @IsOptional() @IsEnum(['Draft', 'Sent', 'Received', 'Cancelled']) status?: string;
  @IsOptional() @IsString() notes?: string;
  @IsOptional() @IsString() expectedDelivery?: string;
  @IsOptional() @IsNumber() @Min(0) unitPrice?: number;
  @IsOptional() @IsNumber() @Min(0) totalAmount?: number;
}
